# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  base-output-directory: $(Agent.BuildDirectory)
pool:
  name: windows2019
  demands:
   - agent.name -equals firstagent

steps:
- checkout: self

- script: |
    #!/bin/bash
    
    # Loop through each directory in the repository
    for dir in */; do
        # Remove trailing slash from directory name
        dir=${dir%*/}
        
        # Check if it's a directory
        if [ -d "$dir" ]; then
            # Copy the directory recursively to another folder
            echo  "$dir" 
        fi
    done
