# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  base-output-directory: $(Agent.BuildDirectory)
pool:
  name: windows2019
  demands:
   - agent.name -equals firstagent

steps:
- checkout: self

- powershell: |
    # Get the current directory
    $currentDirectory = Get-Location

    # Function to recursively list folders and files
    function ListDirectoriesAndFiles($path) {
        # List all directories
        $directories = Get-ChildItem -Path $path -Directory

        # Output each directory
        foreach ($directory in $directories) {
            Write-Host "Directory: $($directory.FullName)"
            # Recursively call the function for subdirectories
            ListDirectoriesAndFiles $directory.FullName
        }

        # List all files
        $files = Get-ChildItem -Path $path -File

        # Output each file
        foreach ($file in $files) {
            Write-Host "File: $($file.FullName)"
        }
    }

    # Call the function for the current directory
    ListDirectoriesAndFiles $currentDirectory
