# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


#trigger:
#- main
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - devs/*
    - prod/sub-prod/*
    

pool:
  name: windows2019
  demands:
   - agent.name -equals firstagent

stages:
  - stage: Lint
    displayName: Format and lint code
    jobs:
      - job: cleaning
        workspace:
          clean: all
        steps:
        
        - checkout: self
          fetchDepth: 0
          fetchTags: true
          persistCredentials: true
      
        - powershell: |
          ## get the changed files
          $files=$(git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion))
          $temp=$files -split ' '
          $count=$temp.Length
          echo "Total changed $count files"
      
        - script: echo Hello, world!
          displayName: 'Run a one-line script'
      
        - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'
