# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  base-output-directory: $(Agent.BuildDirectory)
pool:
  name: windows2019
  demands:
   - agent.name -equals firstagent

steps:
- checkout: self

- powershell: |
    # Function to recursively find and update .b files
    function UpdateBFiles($path) {
        # List all files in the current directory
        $files = Get-ChildItem -Path $path -File -Filter "*.b"

        # Loop through each file
        foreach ($file in $files) {
            Write-Host "Updating $($file.FullName)"
            # Append "new version" to the file
            Add-Content -Path $file.FullName -Value "new version"
        }

        # List all directories
        $directories = Get-ChildItem -Path $path -Directory

        # Recursively call the function for subdirectories
        foreach ($directory in $directories) {
            UpdateBFiles $directory.FullName
        }
    }

    # Call the function for the current directory
    UpdateBFiles (Get-Location).Path