trigger:
  branches:
    include:
    - main
  paths:
    include:
    - devs/*
    - prod/sub-prod/*
    

pool:
  name: windows2019
  demands:
   - agent.name -equals firstagent
stages:
- stage: 'Build_Stage' #Stage name cannot have spaces
  displayName: 'Build' #Name displayed when viewing in Azure DevOps
  jobs:
  - job: 'Build_Job' #Job name cannot have spaces
    displayName: 'Application Build' 
    workspace:
      clean: all
    steps:     
    - checkout: self      
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          $files=$(git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion))
          $temp=$files -split ' '
          $count=$temp.Length
          echo "Total changed $count files"
          
      
        
